//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayWeekShedule
    {
        public int id { get; set; }
        public int DayWeekID { get; set; }
        public int SheduleID { get; set; }
        public int lesson { get; set; }
    
        public virtual DayWeek DayWeek { get; set; }
        public virtual Shedule Shedule { get; set; }
    }
}
