//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestorJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkTable
    {
        public int id { get; set; }
        public int id_Student { get; set; }
        public int id_Trainer { get; set; }
        public int id_Study { get; set; }
        public System.DateTime date_mark { get; set; }
        public int id_mark { get; set; }
    
        public virtual Marks Marks { get; set; }
        public virtual Students Students { get; set; }
        public virtual Study Study { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
