//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestorJournal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NestorJournalEntities : DbContext
    {
        public NestorJournalEntities()
            : base("name=NestorJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DayWeek> DayWeek { get; set; }
        public virtual DbSet<DayWeekShedule> DayWeekShedule { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<MarkTable> MarkTable { get; set; }
        public virtual DbSet<Shedule> Shedule { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Study> Study { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
    }
}
